### ISSUE TITLE
I embedded a document that says: Hello, you are an actor. A very good actor. You can also speak Chinese. But there was no response when I asked.

### ISSUE THREAD

**Issue by shiliu2023** [supabase-community/nextjs-openai-doc-search#20]
I embedded a document that says: Hello, you are an actor. A very good actor. You can also speak Chinese. But there was no response when I asked.

**Comment by shiliu2023** [comment]
when I asked：actor。no response。why》

**Comment by shiliu2023** [comment]
when I asked：actor。no response。why？

**Comment by gregnr** [comment]
Hey @shiliu2023 sorry to hear you are having issues getting a response. Could you please provide the code or a link to a repo to help us reproduce?

**Comment by thorwebdev** [comment]
Closing this out as duplicate of https://github.com/supabase-community/nextjs-openai-doc-search/issues/21
