### ISSUE TITLE
经常出现Sorry, I don't know how to help with that.

### ISSUE THREAD

**Issue by shiliu2023** [supabase-community/nextjs-openai-doc-search#21]
Your familiar environment and people？
Answer:
Sorry, I don't know how to help with that.

Does it mean that Chinese content is not supported?

**Comment by gregnr** [comment]
Hey @shiliu2023, if you are using the same prompt template as the one in this repo, it includes a line that tells GPT to respond with that message:
https://github.com/supabase-community/nextjs-openai-doc-search/blob/ed70e36b109e325da6638fd5fe584019af4cdf47/pages/api/vector-search.ts#L125

Feel free to modify the original prompt/instructions to meet your needs. GPT definitely supports Chinese - perhaps consider writing the prompt itself in Chinese and GPT will likely answer in the same language.
