### ISSUE TITLE
Not able to make this starter project work

### ISSUE THREAD

**Issue by namn-grg** [supabase-community/nextjs-openai-doc-search#23]
# Bug report

## Describe the bug
I followed the exact same steps to locally deploy this starter project but it gives an error

I added my OpenAI key and supabase keys, started my docker and then supabase. I can see the embeddings in the supabase and the openAI API is also working as I can see the usage increasing in the dashboard.

I am not able to get the response as in the screenshot attached -
<img width="1440" alt="Screenshot 2023-05-26 at 1 25 03 PM" src="https://github.com/supabase-community/nextjs-openai-doc-search/assets/97289118/a397b0b9-227c-4ef8-a6e9-614a74540cb3">

The error is -
`CustomEvent {isTrusted: false, data: '{"error":"There was an error processing your request"}', source: SSE, detail: null, type: 'error', …}`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Clone this repo
Did `npm i` to install dependencies
Got the API keys and added them to .env
Set up docker and supabase
then run `pnpm dev`

## Expected behavior
Recieve an error like I am getting

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context
I am not much familiar with supabase and openAI so not sure about this error. Would really appreciate help on this. Also if there is discord support available I can hop there too. I am building a project with very same usecase. Followed @gregnr 's video on youtube

**Comment by thorwebdev** [comment]
This seems to be an error within the vercel edge function. Can you check the logs in your vercel Dashboard please?

**Comment by musashi-garami** [comment]
Yeah I'm getting same behaviour on the 'Deploy direct to vercel starter version' and definitely getting some errors with the edge function "/api/vector-search"

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at (vc/edge/function:50126:3123)
    at (vc/edge/function:120:10949)

**Comment by thorwebdev** [comment]
Can you try [running the project locally](https://github.com/supabase-community/nextjs-openai-doc-search#local-development) and see if that renders any more helpful error messages?

If you need some help with the local development steps, can follow the video guide: https://www.youtube.com/watch?v=xmfNUCjszh4

**Comment by bajajerk** [comment]
i am facing the similar issue on deploying

**Comment by cbtham** [comment]
I encountered this exact error and realized my role key and anon key is missing. Do this:-
1. Run supabase start
2. Run supabase status
3. Copy the service role key and anon key into your env file.
4. Run pnpm dev, it should work now

I am running a local version, not the cloud deploy

**Comment by KalebKloppe** [comment]
Using the supabase keys from `supabase status` in the `.env` I am seeing the same errors.

```
:3000/api/vector-search:1 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

client.js:1
{
    "isTrusted": false,
    "data": "{\"error\":\"There was an error processing your request\"}",
    "source": {...},
        "payload": "{\"query\":\"what are embeddings?\"}",
        "method": "POST",
        "withCredentials": false,
        "FIELD_SEPARATOR": ":",
        "listeners": {...},
        "xhr": null,
        "readyState": 2,
        "progress": 0,
        "chunk": ""
    }
}
```

```
[TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))]
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (1673kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
[TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))]
```


Edit: The issue was the OpenAI.

Despite having given them my payment info and generated an API key, I needed to *enable* the api by 
- visiting https://platform.openai.com/account, 
- going to  `Billing > Overview`
- clicking the `Set up paid account` button
- re-entering my billing info

**Comment by thorwebdev** [comment]
Thanks for outlining the resolution steps. Closing this out.
