### ISSUE TITLE
Sorry, I don't know how to help with that.

### ISSUE THREAD

**Issue by d3287t328** [supabase-community/nextjs-openai-doc-search#26]
# Bug report

## Describe the bug

Followed setup instructions and the only responses I get are "Sorry, I don't know how to help with that." 

## Additional context

There are no additional error messages in the console.

![image](https://github.com/supabase-community/nextjs-openai-doc-search/assets/125713831/f7827cb7-9400-4eb7-9988-8bd3304e7a6b)

**Comment by d3287t328** [comment]
I solved my issue with a few changes:

Manually installed pnpm manually: ```curl -fsSL https://get.pnpm.io/install.sh | sh -``` in my opinion this is an annoying dependency and would be simpler to not use, any idea why it is used?

```
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
Failed to generate completion: {"error":{"message":"The server had an error while processing your request. Sorry about that!","type":"server_error","param":null,"code":null}}
```
To solve this warning message I had to create a new file in components:

```
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'snip'
const supabaseKey = 'snip'

const supabase = createClient(supabaseUrl, supabaseKey, {
  persistSession: true,         // add persistSession here
  localStorage: window.localStorage,   // storage option 
})
```

There are a couple of issues with output still. My source is in standard markdown files and the markdown does not get stripped out properly per this image. Also there is no scroll up option in the chat window making earlier generated content unreadable. It also seems to sometimes produce more output then needed.

**Comment by thorwebdev** [comment]
This example doesn't use any auth, therefore `persistSession` needs to be set to `false`.
