### ISSUE TITLE
Long replies breaks the app

### ISSUE THREAD

**Issue by musashi-garami** [supabase-community/nextjs-openai-doc-search#40]
If the app gives a lengthy reply, the dialogue goes full screen, but is not scrollable nor is the browser zoomable.

I've tried using some tailwinds overflow-auto and overflow-scrolls. but doesn't seem to change anything.

Surely this has been experienced by other users when lengthy replies are given >?

**Comment by gregnr** [comment]
Good catch @musashi-garami. Would love a PR to help resolve!

**Comment by musashi-garami** [comment]
Just made my first ever pull request, not sure if I did it right. I forked this repo and changed the code in my forked version. (I have a private repo with many changes that's not forked, was made with the auto deploy function of this (the deploy to vercel process).

I changed the code to fix this, made a pull request for myself. Accepted, then made a pull request for this ?

If I did something wrong, please let me know.. But exciting doing first pull request!

**Comment by gregnr** [comment]
PR looks great @musashi-garami. Thanks for contributing!
