### ISSUE TITLE
New user of supabase, how can I add datas and files STEP BY STEP  into supabase and let them connect with my website?

### ISSUE THREAD

**Issue by deepchatwithai** [supabase-community/nextjs-openai-doc-search#7]
# Improve documentation

Supabase is  a great product!

well, for new user of supabase, it's not quite clear HOW TO Make IT WORK  on vercel.

I deployed on vercel, and changed the openai api key in repo. then deployed again.

 But the search result is always 'Sad news, the search has failed! Please try again.'

what shall I do to make it work?

Change the url, anon key and role key?

**Comment by deepchatwithai** [comment]
# supabase start
-bash: supabase: command not found 

this result all the time

I'm sure I have installed docker and run it in linux.
Any one could help me : (

**Comment by toanbku** [comment]
I believe that your OpenAI account has run out of balance, resulting in the inability to perform queries. You can try checking your account here https://platform.openai.com/account/usage

**Comment by gregnr** [comment]
Hi @deepchatwithai! A few things we need to debug here:
1. How is your project structured? Is it based off a template or tutorial? Is your repo public & can you link it here so we can help debug?
2. OpenAI keys shouldn't be used client side. Are you making requests to OpenAI directly from your client, or through a server (eg. edge function)?
3. For the `supabase` CLI, confirming that you have installed it using [these instructions](https://supabase.com/docs/guides/cli#installation)? If you install via `npm`, you should prefix each command with `npx`:
    ```shell
    npx supabase ...
    ```

**Comment by deepchatwithai** [comment]
> Hi @deepchatwithai! A few things we need to debug here:
> 
> 1. How is your project structured? Is it based off a template or tutorial? Is your repo public & can you link it here so we can help debug?
> 2. OpenAI keys shouldn't be used client side. Are you making requests to OpenAI directly from your client, or through a server (eg. edge function)?
> 3. For the `supabase` CLI, confirming that you have installed it using [these instructions](https://supabase.com/docs/guides/cli#installation)? If you install via `npm`, you should prefix each command with `npx`:
>    ```shell
>    npx supabase ...
>    ```

Thanks so much for your reply!

I'll try npx prefix first - -! 

never used this before...

My test site was build up with vercel template, and had been reset last week.

I'll try it again. 

and I suppose that the doc shall be vectored into supabase first, then the frontend could search after vectoring finished. Since I failed in vectoring docs, the frontend can't get any data.

Is my suppose be right?  

Anyway, I'll try again and thanks so much for your reply and for the great work of supabase!

**Comment by gregnr** [comment]
Yep - you'll need to pre-process your docs (create embeddings + store in DB) first. Let me know if that works!

**Comment by ghost** [comment]
Hello guys,
I am having the same issue trying to make it run. Actually, my node_module directory was missing - not a problem, but when I tried running `npm install`  I got this:

```
@PublicTrades ➜ /workspaces/nextjs-openai-doc-search-starter (main) $ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: class-variance-authority@0.4.0
npm ERR! Found: typescript@5.0.2
npm ERR! node_modules/typescript
npm ERR!   typescript@"5.0.2" from the root project
npm ERR!   peerOptional typescript@">=3.3.1" from eslint-config-next@13.2.4
npm ERR!   node_modules/eslint-config-next
npm ERR!     eslint-config-next@"13.2.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@">= 4.5.5 < 5" from class-variance-authority@0.4.0
npm ERR! node_modules/class-variance-authority
npm ERR!   class-variance-authority@"^0.4.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@">= 4.5.5 < 5" from class-variance-authority@0.4.0
npm ERR!   node_modules/class-variance-authority
npm ERR!     class-variance-authority@"^0.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/codespace/.npm/_logs/2023-05-25T03_35_55_229Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2023-05-25T03_35_55_229Z-debug-0.log
@PublicTrades ➜ /workspaces/nextjs-openai-doc-search-starter (main) $ 
```

I am working on it via codespace, would this be the reason?

**Comment by thorwebdev** [comment]
You can find a step by step video guide here: https://youtu.be/xmfNUCjszh4
