### ISSUE TITLE
Deployment Fails When Trying to Deploy Template From Vercel.ai Page

### ISSUE THREAD

**Issue by Benanna2019** [supabase-community/nextjs-openai-doc-search#8]
# Bug report

## Describe the bug

When I go to [vercel.ai](https://www.vercel.ai) and choose this template to deploy, and start the process, it fails immediately and wont deploy with alteration to build step or change in code. If I change it to look to the right directory, the `pages` directory, I get another build error in `api/vector-search.js` because there are unsupported modules

## To Reproduce

1. Go to [vercel.ai](https://www.vercel.ai)
2. Scroll down to and click on 'OpenAI Doc Search Start'
3. Click Deploy
4. Go through deployment steps on the vercel dashboard (set up a supabase project and then get an openai key)
5. Then deploy
6. In a second or so you will see build failed due 'The specified Root Directory 'app' does not exist'
7. Go into the project settings for you newly created project 
8. Adjust the root directory to be `pages` 
9. Redeploy
10. You will then see, after a few promising seconds, `The edge function 'api/vector-search.js' is referencing unsupported modules'`

## Expected behavior

- The template to be deployed. 

## Screenshots

- Build Fail 1

<img width="1221" alt="Screen Shot 2023-04-08 at 10 36 09 AM" src="https://user-images.githubusercontent.com/65513685/230728247-7ef1fd26-00e2-4917-a732-17ec52ecb1e0.png">

- Build Fail 2

<img width="1240" alt="Screen Shot 2023-04-08 at 10 35 47 AM" src="https://user-images.githubusercontent.com/65513685/230728245-4a77a135-3fe0-4924-b519-2c3fb5cd9e5b.png">

**Comment by thorwebdev** [comment]
Thanks for reporting this. I'm working with @steven-tey to get this fixed. Will update here once done.

**Comment by thorwebdev** [comment]
This has been resolved.
